# Generated by Django 4.1.4 on 2022-12-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('date', models.DateField()),
                ('paid', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.batch')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.payment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
