# Generated by Django 4.1.4 on 2022-12-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_payment_admission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid',
            new_name='payment_successful',
        ),
        migrations.AlterField(
            model_name='batch',
            name='time',
            field=models.CharField(choices=[('M1', '6-7 AM'), ('M2', '7-8 AM'), ('M3', '8-9 AM'), ('E', '5-6 PM')], max_length=20),
        ),
    ]
