# Generated by Django 4.1.4 on 2022-12-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_batch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='time',
            field=models.CharField(choices=[('M', '6-7 AM'), ('M', '7-8 AM'), ('M', '8-9 AM'), ('E', '5-6 PM')], max_length=1),
        ),
    ]
