# Generated by Django 4.1.4 on 2022-12-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_batch_id_admission_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='batch',
            new_name='batch_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='batch',
            new_name='batch_id',
        ),
    ]
