# Generated by Django 4.1.4 on 2022-12-12 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_batch_id_admission_batch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user',
        ),
    ]
