# Generated by Django 4.1.4 on 2022-12-12 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_payment_id_admission_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='payment',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='user_id',
        ),
    ]
